Tabarez
spardo83/sudoku-android pull request #5
Opened 2021-06-11 15:09 UTC by brtab

2021-06-11 23:40 UTC, spardo83 requested changes

2021-06-11 23:40 UTC, spardo83 commented on app/src/main/java/ar/edu/unlam/sudoku/MainActivity.kt
> +        binding.nuevoJuego.setOnClickListener {
Los click listeners los pondría en una función separada, nos va a permitir tener el código más prolijo

2021-06-11 23:40 UTC, spardo83 commented on app/src/main/res/layout/activity_main.xml
> +        android:gravity="center"
Acá sacaría el gravity porque no aplica para el ConstraintLayout

2021-06-11 23:40 UTC, spardo83 commented on app/src/main/res/layout/activity_sudoku.xml
>      <View
No tiene constraints, creo que se va a ir a la parte de arriba a la izquierda cuando se ejecute

2021-06-12 21:13 UTC, brtab commented on app/src/main/res/layout/activity_main.xml
> +        android:gravity="center"
ah ok, asi si estaria bien aplicado?
<TextView
        android:id="@+id/titulo"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="24dp"
        android:gravity="center"
        android:text="SUDOKU"
        android:textAppearance="@style/TextAppearance.AppCompat.Large"
        android:textColor="@color/white"
        android:textSize="30dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

2021-06-12 21:14 UTC, brtab commented on app/src/main/res/layout/activity_main.xml
> +        android:gravity="center"
ah ok, y asi si estaria bien aplicado?
TextView
        android:id="@+id/titulo"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="24dp"
        android:gravity="center"
        android:text="SUDOKU"
        android:textAppearance="@style/TextAppearance.AppCompat.Large"
        android:textColor="@color/white"
        android:textSize="30dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"

2021-06-13 17:29 UTC, brtab commented on app/src/main/res/layout/activity_sudoku.xml
>      <View
ah ese no lo tengo, lo habre borrado cuando saque los constraint sin querer..

2021-06-14 23:23 UTC, briezeba commented
@brtab este branch quedo desactualizado. Fijate de actualizarlo con lo que hay hoy en dia en master para evitar conflictos al querer mergear :D

2021-06-15 00:22 UTC, briezeba commented
> @brtab este branch quedo desactualizado. Fijate de actualizarlo con lo que hay hoy en dia en master para evitar conflictos al querer mergear :D

Arreglado!

2021-06-15 00:25 UTC, briezeba commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" default="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
No le cambiaria el JDK por las dudas

2021-06-16 15:56 UTC, escobarm90 approved these changes
ok

2021-06-23 20:15 UTC, spardo83 requested changes

2021-06-23 20:15 UTC, spardo83 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="48dp"
Queremos un tamaño fijo en los buttons?

2021-06-23 20:15 UTC, spardo83 commented on app/src/main/res/values/colors.xml
> +    <color name="background2">#8888F9</color>
background2 que representa? podemos ponerle quizás un nombre más representativo?

2021-06-23 20:15 UTC, spardo83 commented on app/src/main/res/values/strings.xml
> +    <string name="textoIngresarNumero">Numero a ingresar</string>
trataría de seguir un standard de snake case, en lugar de camel case

2021-06-23 20:15 UTC, spardo83 commented on app/build.gradle
> +    buildFeatures{
Necesitamos ambos? con uno solo no nos alcanza?
[Documentación](https://developer.android.com/topic/libraries/data-binding/start)

2021-06-23 21:55 UTC, escobarm90 approved these changes

2021-06-23 21:57 UTC, escobarm90 reviewed
ok

2025-06-10 19:00 UTC, closed without merging